general:
  data_dir: "data"
  logs_dir: "logs"
  debug_log: "app.log"

ssh:
  devices:
    - hostname: "host-01"
      ip_address: "192.168.50.201"
      port: 22
      username: "user01"
      password: "user01"
      commands_file: "data/commands/commands_device_1.txt"
    - hostname: "host-02"
      ip_address: "192.168.50.202"
      port: 22
      username: "user02"
      password: "user02"
      commands_file: "data/commands/commands_device_2.txt"